image: python

stages:
- earlytest
- fulltest
- deploy

before_script:
- git submodule sync --recursive
- git submodule update --init --recursive
- curl -O https://bootstrap.pypa.io/get-pip.py
- python get-pip.py
- pip install -r dev-requirements.txt

pylint:
  image: python:3.7
  stage: earlytest
  script: tox -e pylint

pep8:
  stage: earlytest
  script: tox -e pep8

python2:
  image: python:2.7
  stage: earlytest
  script: tox -e py27

python3:
  image: python:3.7
  stage: earlytest
  script: tox -e py37

python34:
  image: python:3.4
  stage: fulltest
  script: tox -e py34

python35:
  image: python:3.5
  stage: fulltest
  script: tox -e py35

python36:
  image: python:3.6
  stage: fulltest
  script: tox -e py36

python38:
  image: python:3.8
  stage: fulltest
  script: tox -e py38

pythonrc:
  image: python:rc
  stage: fulltest
  script: tox -e py39

pypy:
  image: pypy:2
  stage: fulltest
  script: tox -e pypy

pypy3:
  image: pypy:3
  stage: fulltest
  script: tox -e pypy3

coveralls:
  image: python:3.7
  variables:
    CI_NAME: gitlab
    CI_BUILD_NUMBER: "${CI_JOB_ID}"
    CI_BUILD_URL: "${CI_JOB_URL}"
    CI_BRANCH: "${CI_COMMIT_REF_NAME}"
  stage: deploy
  script:
    - pip install coveralls
    - pip install submodules/*
    - coverage run --source=cryptolyzer setup.py test
    - coveralls
  only:
    refs:
      - master

dockerhub:
  image: docker:latest
  stage: deploy
  services:
    - docker:dind
  variables:
    DOCKER_NAME: coroner/${CI_PROJECT_NAME}
    GIT_SUBMODULE_STRATEGY: recursive
  before_script:
    - if ! [ -z ${CI_COMMIT_TAG} ] ; then DOCKER_NAME="${DOCKER_NAME}:${CI_COMMIT_TAG}" ; fi
    - echo "${CI_REGISTRY_PASSWORD}" | docker login -u "${CI_REGISTRY_USER}" --password-stdin "${CI_REGISTRY}"
  script:
    - docker build -t "$DOCKER_NAME" .
    - docker push "$DOCKER_NAME"
  only:
    refs:
      - branches
      - tags
    variables:
      - $CI_COMMIT_TAG =~ /^v\d+.\d+.\d+$/
      - $CI_COMMIT_REF_NAME == "master"

obs:
  image: coroner/cryptolyzer:obs
  stage: deploy
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - obs.sh
  only:
    refs:
      - branches
      - tags
    variables:
      - $CI_COMMIT_TAG =~ /^v\d+.\d+.\d+$/
      - $CI_COMMIT_REF_NAME == "master"
